# Generated by Django 4.2.3 on 2024-02-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_management", "0002_alter_foodcategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodcategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
