# Generated by Django 4.2.3 on 2024-02-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_management", "0003_alter_foodcategory_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "kg"),
                    ("g", "g"),
                    ("ml", "ml"),
                    ("pieces", "pieces"),
                    ("packets", "packets"),
                    ("litres", "litres"),
                    ("units", "units"),
                    ("other", "other"),
                ],
                default="kg",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
