# Generated by Django 4.2.3 on 2024-02-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_management", "0004_fooditem_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodcategory",
            name="pre_expiry_days",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
