# Generated by Django 4.2.3 on 2024-02-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_management", "0006_foodbank"),
    ]

    operations = [
        migrations.CreateModel(
            name="BarcodeFoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("expiry_date", models.DateField()),
            ],
        ),
    ]
