# Generated by Django 4.2.3 on 2024-02-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_management", "0007_barcodefooditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="barcodefooditem",
            name="barcode_image",
            field=models.ImageField(default=0, upload_to="barcode_images/"),
            preserve_default=False,
        ),
    ]
